// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/documents": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/documents";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "./routes/documents.tsx": {
    id: "routes/documents";
    page: "/documents";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.tsx");
  "routes/documents": typeof import("./app/./routes/documents.tsx");
};